### PR TITLE
review for inclusion request into conan-center

### PR DESCRIPTION
**Pull request by pvicente**
See comments: 
- https://github.com/bincrafters/community/issues/175

CC: @SSE4  @solvingj

### CODE REVIEW

**Comment by solvingj** [comment]
Thanks for the great PR's! 
I think this one should be `pure_c=True` also.

**Review by ghost — APPROVED** [review]
Perfect. Thanks a lot!

**Comment by pvicente** [comment]
@solvingj  I saw that [pure_c=True](https://github.com/bincrafters/bincrafters-package-tools/blob/master/bincrafters/build_template_default.py#L9) is enabled by default, but I can set it to be more clear (explicit better than implicit)

If you are ok could you please MR it. I have another [PR for conan-flac](https://github.com/bincrafters/conan-flac/pull/1) which is failing because it needs binaries generated by conan-ogg (this PR).

**Comment by pvicente** [comment]
@solvingj @dimi309  @ZaMaZaN4iK any plans about merging it today? I need the binaries generated by these changes for [flac PR](https://github.com/bincrafters/conan-flac/pull/1)

**Comment by solvingj** [comment]
@pvicente Thank you so much for the commits.  everyone's just busy lately, i will work on this now and restart the flac jobs assuming this one passes.

**Pull request merged**
